apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: final
  name: db-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: db
        image: 334109771446.dkr.ecr.us-east-1.amazonaws.com/mysqldb:latest
        env:
        #- name: MYSQL_USER
         # valueFrom:
          #  secretKeyRef:
           #   name: db-sec
            #  key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-sec
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      imagePullSecrets:
      - name: db-ecr
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
   