apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: final
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2-csi
