apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: CLO835-role-binding
  namespace: final
subjects:
  - kind: ServiceAccount
    name: clo835
    namespace: final
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: CLO835